version: "3"
services:
  postgresdb:
    image: postgres:12.3
    container_name: postgres_english_train_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: haxul
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: english_train
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
